Add kafka to minikube

diff --git a/k8s/templates/kafka-statefulset.yaml b/k8s/templates/kafka-statefulset.yaml
--- a/k8s/templates/kafka-statefulset.yaml
+++ b/k8s/templates/kafka-statefulset.yaml
@@ -29,38 +29,42 @@ spec:
             - key: kafka_server_jaas.conf
               path: kafka_server_jaas.conf
               mode: 0555
-      initContainers:
-        - name: check-zk
-          image: {{ .Values.deployer.image }} # using deployer image for initContainer
-          command:
-            - 'sh'
-            - '-c'
-            - |
-              COUNTER=0;
-              while [  $COUNTER -lt 120 ]; do
-                addr=$(nslookup -type=a minikube-zk-client | grep "Address:" | awk 'NR>1 {print $2}')
-                if [ ! -z "$addr" ]; then
-                  while read -r line; do
-                    echo $line;
-                    mode=$(echo srvr | nc $line 2181 | grep "Mode");
-                    echo $mode;
-                    if [ "$mode" = "Mode: leader" ] || [ "$mode" = "Mode: standalone" ]; then
-                      echo "Found a leader!";
-                      exit 0;
-                    fi;
-                  done <<EOF
-              $addr
-              EOF
-                fi;
-                let COUNTER=COUNTER+1;
-                sleep 2;
-              done;
-              echo "Did NOT see a ZK leader after 240 secs!";
-              exit 1;
+      # initContainers:
+      #   - name: check-zk
+      #     image: {{ .Values.deployer.image }} # using deployer image for initContainer
+      #     # run a script to find the zookeeper leader, failed the step if no leader is found
+      #     # essentially deploy kafka after zookeeper is ready
+      #     # may not be necessary if deploy manually
+      #     command:
+      #       - 'sh'
+      #       - '-c'
+      #       - |
+      #         COUNTER=0;
+      #         while [  $COUNTER -lt 120 ]; do
+      #           addr=$(nslookup -type=a minikube-zk-client | grep "Address:" | awk 'NR>1 {print $2}')
+      #           if [ ! -z "$addr" ]; then
+      #             while read -r line; do
+      #               echo $line;
+      #               mode=$(echo srvr | nc $line 2181 | grep "Mode");
+      #               echo $mode;
+      #               if [ "$mode" = "Mode: leader" ] || [ "$mode" = "Mode: standalone" ]; then
+      #                 echo "Found a leader!";
+      #                 exit 0;
+      #               fi;
+      #             done <<EOF
+      #         $addr
+      #         EOF
+      #           fi;
+      #           let COUNTER=COUNTER+1;
+      #           sleep 2;
+      #         done;
+      #         echo "Did NOT see a ZK leader after 240 secs!";
+      #         exit 1;
       containers:
         - name: kafka
-          image: "{{ .Values.kafka.image.repo }}:{{ .Values.kafka.image.tag }}" # something like marketplace xxx kafka:2.8
-          imagePullPolicy: IfNotPresent
+          image: marketplace.gcr.io/google/kafka:2.8
+          # image: "{{ .Values.kafka.image.repo }}:{{ .Values.kafka.image.tag }}" # something like marketplace xxx kafka:2.8
+          imagePullPolicy: Never
           ports:
             - name: kafka-client
               containerPort: 9092
@@ -70,30 +74,30 @@ spec:
             - name: BROKER_POD_IP
               valueFrom:
                 fieldRef:
-                  fieldPath: status.podIP
+                  fieldPath: status.podIP # retrieve dynamically from metadata
             - name: BROKER_POD_NAME
               valueFrom:
                 fieldRef:
-                  fieldPath: metadata.name
+                  fieldPath: metadata.name # ??
             - name: POD_NAMESPACE
               valueFrom:
                 fieldRef:
-                  fieldPath: metadata.namespace
+                  fieldPath: metadata.namespace # default
             - name: STAS_DELAY
               value: "30"
             - name: KAFKA_INTER_BROKER_LISTENER_NAME
               value: "INTERNAL"
             - name: BROKER_ID_COMMAND
-              value: "hostname | sed s/{{ .Release.Name }}-kafka-//"
+              value: "hostname | sed s/minikube-kafka-//"
             - name: KAFKA_LISTENERS
-              value: "INTERNAL://$(BROKER_POD_IP):9093,CLIENT://$(BROKER_POD_NAME).{{ .Release.Name }}-kafka-headless.{{ .Release.Namespace }}.svc.cluster.local:9092"
+              value: "INTERNAL://$(BROKER_POD_IP):9093,CLIENT://$(BROKER_POD_NAME).minikube-kafka-headless.default.svc.cluster.local:9092"
             - name: KAFKA_ADVERTISED_LISTENERS
-              value: "INTERNAL://$(BROKER_POD_IP):9093,CLIENT://$(BROKER_POD_NAME).{{ .Release.Name }}-kafka-headless.{{ .Release.Namespace }}.svc.cluster.local:9092"
+              value: "INTERNAL://$(BROKER_POD_IP):9093,CLIENT://$(BROKER_POD_NAME).minikube-kafka-headless.default.svc.cluster.local:9092"
             - name: KAFKA_LOG_DIRS
               value: "/kafka/logs"
             - name: KAFKA_ZOOKEEPER_CONNECT
               value: "minikube-zk-client.default.svc.cluster.local:2181" # use "default" for minikube testing
-            - name: KAFKA_OPTS
+            - name: KAFKA_OPTS # optional configuration scripts
               value: "-Djava.security.auth.login.config=/tmp/kafka_server_jaas.conf"
             - name: KAFKA_SASL_ENABLED_MECHANISMS
               value: "PLAIN"
